version: 2

updates:
  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: weekly
    target-branch: dev
    open-pull-requests-limit: 5
    groups:
      api-minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    target-branch: dev
    open-pull-requests-limit: 5
    groups:
      web-minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    open-pull-requests-limit: 5
    groups:
      actions:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    labels:
      - dependencies
