name-template: 'v$NEXT_PATCH - Release Drafter'
tag-template: 'v$NEXT_PATCH'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'ci'
      - 'refactor'
change-template: '- $TITLE #$NUMBER by @$AUTHOR'
template: |
  ## Changelog

  $CHANGES
prerelease: true
