import { PrismaClient, CellarType, BottleCategory } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // ─── Users ───────────────────────────────────────────────────────────────────
  // Seed onto the first existing admin, or create a fallback if none exists.

  let admin = await prisma.user.findFirst({
    where: { isAdmin: true },
    orderBy: { createdAt: 'asc' },
  });

  if (!admin) {
    const passwordHash = await bcrypt.hash('Demo1234!demo', 12);
    admin = await prisma.user.create({
      data: {
        email: 'admin@glou.app',
        username: 'admin',
        passwordHash,
        displayName: 'Admin',
        isAdmin: true,
        isActive: true,
        language: 'FR',
      },
    });
    console.log(`✅ Created fallback admin: ${admin.username}`);
  } else {
    console.log(`✅ Seeding onto existing admin: ${admin.username} <${admin.email}>`);
  }

  // Keep a reference for the demo items — reuse admin if no second user exists
  const user = admin;

  // ─── Cellars ─────────────────────────────────────────────────────────────────

  const cellars = await Promise.all([
    prisma.cellar.upsert({
      where: { id: 'cellar-cave-enterree' },
      update: {},
      create: {
        id: 'cellar-cave-enterree',
        userId: admin.id,
        name: 'Cave enterrée',
        description: 'Cave de vieillissement principale — 12°C constant, 75% humidité',
        type: CellarType.VINTAGE,
        columns: 12,
        rows: 10,
        hotZoneRows: 2,
        coldZoneRows: 2,
      },
    }),
    prisma.cellar.upsert({
      where: { id: 'cellar-armoire-temp' },
      update: {},
      create: {
        id: 'cellar-armoire-temp',
        userId: admin.id,
        name: 'Armoire à vin',
        description: 'EuroCave Pro — double zone 8-18°C',
        type: CellarType.COOLER,
        columns: 6,
        rows: 8,
        hotZoneRows: 3,
        coldZoneRows: 3,
      },
    }),
    prisma.cellar.upsert({
      where: { id: 'cellar-etagere-salon' },
      update: {},
      create: {
        id: 'cellar-etagere-salon',
        userId: admin.id,
        name: 'Étagère salon',
        description: 'Bouteilles en service et spiritueux',
        type: CellarType.SHELF,
        columns: 8,
        rows: 4,
      },
    }),
    prisma.cellar.upsert({
      where: { id: 'cellar-cave-bordeaux' },
      update: {},
      create: {
        id: 'cellar-cave-bordeaux',
        userId: admin.id,
        name: 'Section Bordeaux',
        description: 'Dédiée aux grands crus bordelais',
        type: CellarType.VINTAGE,
        columns: 10,
        rows: 8,
        coldZoneRows: 3,
      },
    }),
    prisma.cellar.upsert({
      where: { id: 'cellar-demo-user' },
      update: {},
      create: {
        id: 'cellar-demo-user',
        userId: user.id,
        name: 'Ma petite cave',
        description: 'Cave à vins personnelle',
        type: CellarType.VINTAGE,
        columns: 6,
        rows: 6,
      },
    }),
  ]);

  console.log(`✅ Cellars: ${cellars.length}`);

  // ─── Collections ─────────────────────────────────────────────────────────────

  const colInvestissement = await prisma.collection.upsert({
    where: { id: 'col-investissement' },
    update: {},
    create: {
      id: 'col-investissement',
      userId: admin.id,
      name: 'Investissement',
      color: '#f59e0b',
      icon: 'TrendingUp',
    },
  });

  const colCadeaux = await prisma.collection.upsert({
    where: { id: 'col-cadeaux' },
    update: {},
    create: {
      id: 'col-cadeaux',
      userId: admin.id,
      name: 'Cadeaux reçus',
      color: '#ec4899',
      icon: 'Gift',
    },
  });

  const colCoups = await prisma.collection.upsert({
    where: { id: 'col-coups-coeur' },
    update: {},
    create: {
      id: 'col-coups-coeur',
      userId: admin.id,
      name: 'Coups de cœur',
      color: '#ef4444',
      icon: 'Heart',
    },
  });

  const colDegustation = await prisma.collection.upsert({
    where: { id: 'col-degustation' },
    update: {},
    create: {
      id: 'col-degustation',
      userId: admin.id,
      name: 'Club dégustation',
      color: '#8b5cf6',
      icon: 'Users',
    },
  });

  const colFetes = await prisma.collection.upsert({
    where: { id: 'col-fetes' },
    update: {},
    create: {
      id: 'col-fetes',
      userId: admin.id,
      name: 'Fêtes & occasions',
      color: '#06b6d4',
      icon: 'Sparkles',
    },
  });

  console.log(`✅ Collections: 5`);

  // ─── Inventory Items ──────────────────────────────────────────────────────────

  // Helper
  const cellarMain = cellars[0].id;
  const cellarCooler = cellars[1].id;
  const cellarShelf = cellars[2].id;
  const cellarBordeaux = cellars[3].id;

  // ── VINS ROUGES ───────────────────────────────────────────────────────────────

  const redWines = [
    {
      name: 'Château Pétrus',
      producer: 'Château Pétrus',
      vintage: 2015,
      region: 'Pomerol',
      color: 'red',
      grapeVarieties: ['Merlot'],
      alcoholDegree: 14.5,
      bottleSize: '75cl',
      purchasePrice: 3200,
      estimatedValue: 4100,
      peakMaturityFrom: 2025,
      peakMaturityTo: 2050,
      serviceTemp: '17-18°C',
      needsAeration: true,
      cellarId: cellarBordeaux,
      tags: ['grand cru', 'pomerol', 'prestige'],
      notes: 'Nez intense de truffe noire et de cassis. Tanins veloutés exceptionnels.',
    },
    {
      name: 'Château Margaux',
      producer: 'Château Margaux',
      vintage: 2016,
      region: 'Margaux',
      color: 'red',
      grapeVarieties: ['Cabernet Sauvignon', 'Merlot', 'Petit Verdot'],
      alcoholDegree: 13.5,
      bottleSize: '75cl',
      purchasePrice: 850,
      estimatedValue: 1100,
      peakMaturityFrom: 2026,
      peakMaturityTo: 2055,
      serviceTemp: '17-18°C',
      needsAeration: true,
      cellarId: cellarBordeaux,
      tags: ['premier cru', 'bordeaux', 'prestige'],
      notes: 'Grande finesse et élégance. Millésime exceptionnel.',
    },
    {
      name: 'Château Mouton Rothschild',
      producer: 'Baron Philippe de Rothschild',
      vintage: 2018,
      region: 'Pauillac',
      color: 'red',
      grapeVarieties: ['Cabernet Sauvignon', 'Merlot', 'Cabernet Franc'],
      alcoholDegree: 14.0,
      bottleSize: '75cl',
      purchasePrice: 650,
      estimatedValue: 850,
      peakMaturityFrom: 2028,
      peakMaturityTo: 2060,
      serviceTemp: '17-18°C',
      needsAeration: true,
      cellarId: cellarBordeaux,
      tags: ['premier cru', 'pauillac'],
    },
    {
      name: 'Château Léoville-Las Cases',
      producer: 'Château Léoville-Las Cases',
      vintage: 2014,
      region: 'Saint-Julien',
      color: 'red',
      grapeVarieties: ['Cabernet Sauvignon', 'Merlot', 'Cabernet Franc'],
      alcoholDegree: 13.5,
      bottleSize: '75cl',
      purchasePrice: 220,
      estimatedValue: 310,
      peakMaturityFrom: 2024,
      peakMaturityTo: 2045,
      serviceTemp: '16-18°C',
      needsAeration: true,
      cellarId: cellarBordeaux,
      tags: ['deuxième cru', 'saint-julien'],
    },
    {
      name: 'Romanée-Conti Grand Cru',
      producer: 'Domaine de la Romanée-Conti',
      vintage: 2019,
      region: 'Vosne-Romanée',
      color: 'red',
      grapeVarieties: ['Pinot Noir'],
      alcoholDegree: 14.0,
      bottleSize: '75cl',
      purchasePrice: 14000,
      estimatedValue: 18500,
      peakMaturityFrom: 2030,
      peakMaturityTo: 2060,
      serviceTemp: '16-17°C',
      needsAeration: false,
      cellarId: cellarMain,
      tags: ['grand cru', 'bourgogne', 'ultra-prestige', 'investissement'],
      notes: 'Le pinacle de la Bourgogne. Millesime 2019 exceptionnel.',
    },
    {
      name: 'Gevrey-Chambertin 1er Cru Clos Saint-Jacques',
      producer: 'Domaine Rousseau',
      vintage: 2017,
      region: 'Gevrey-Chambertin',
      color: 'red',
      grapeVarieties: ['Pinot Noir'],
      alcoholDegree: 13.0,
      bottleSize: '75cl',
      purchasePrice: 280,
      estimatedValue: 380,
      peakMaturityFrom: 2025,
      peakMaturityTo: 2040,
      serviceTemp: '16-17°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['premier cru', 'bourgogne', 'pinot noir'],
    },
    {
      name: 'Chambolle-Musigny Les Amoureuses',
      producer: 'J.F. Mugnier',
      vintage: 2018,
      region: 'Chambolle-Musigny',
      color: 'red',
      grapeVarieties: ['Pinot Noir'],
      alcoholDegree: 13.5,
      bottleSize: '75cl',
      purchasePrice: 320,
      estimatedValue: 420,
      peakMaturityFrom: 2026,
      peakMaturityTo: 2042,
      serviceTemp: '15-17°C',
      needsAeration: false,
      cellarId: cellarMain,
      tags: ['premier cru', 'bourgogne', 'élégant'],
    },
    {
      name: 'Crozes-Hermitage',
      producer: 'M. Chapoutier',
      vintage: 2020,
      region: 'Crozes-Hermitage',
      color: 'red',
      grapeVarieties: ['Syrah'],
      alcoholDegree: 13.5,
      bottleSize: '75cl',
      purchasePrice: 28,
      estimatedValue: 32,
      peakMaturityFrom: 2023,
      peakMaturityTo: 2030,
      serviceTemp: '16-17°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['rhône', 'syrah', 'rapport qualité-prix'],
    },
    {
      name: 'Hermitage La Chapelle',
      producer: 'Paul Jaboulet Aîné',
      vintage: 2012,
      region: 'Hermitage',
      color: 'red',
      grapeVarieties: ['Syrah'],
      alcoholDegree: 14.0,
      bottleSize: '75cl',
      purchasePrice: 180,
      estimatedValue: 280,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2040,
      serviceTemp: '17-18°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['rhône nord', 'syrah', 'icônique'],
    },
    {
      name: 'Bandol Rouge Château Pibarnon',
      producer: 'Château de Pibarnon',
      vintage: 2018,
      region: 'Bandol',
      color: 'red',
      grapeVarieties: ['Mourvèdre', 'Grenache'],
      alcoholDegree: 14.5,
      bottleSize: '75cl',
      purchasePrice: 45,
      estimatedValue: 58,
      peakMaturityFrom: 2025,
      peakMaturityTo: 2038,
      serviceTemp: '16-18°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['provence', 'mourvèdre'],
    },
    {
      name: 'Châteauneuf-du-Pape Château Rayas',
      producer: 'Château Rayas',
      vintage: 2016,
      region: 'Châteauneuf-du-Pape',
      color: 'red',
      grapeVarieties: ['Grenache'],
      alcoholDegree: 14.5,
      bottleSize: '75cl',
      purchasePrice: 350,
      estimatedValue: 550,
      peakMaturityFrom: 2024,
      peakMaturityTo: 2045,
      serviceTemp: '17-18°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['rhône sud', 'grenache', 'prestige'],
    },
    {
      name: 'Barolo Brunate',
      producer: 'Giuseppe Mascarello',
      vintage: 2016,
      region: 'Barolo',
      color: 'red',
      grapeVarieties: ['Nebbiolo'],
      alcoholDegree: 14.5,
      bottleSize: '75cl',
      purchasePrice: 95,
      estimatedValue: 140,
      peakMaturityFrom: 2026,
      peakMaturityTo: 2046,
      serviceTemp: '18°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['italie', 'piémont', 'nebbiolo', 'barolo'],
    },
    {
      name: 'Brunello di Montalcino Riserva',
      producer: 'Biondi-Santi',
      vintage: 2013,
      region: 'Montalcino',
      color: 'red',
      grapeVarieties: ['Sangiovese Grosso'],
      alcoholDegree: 14.0,
      bottleSize: '75cl',
      purchasePrice: 280,
      estimatedValue: 420,
      peakMaturityFrom: 2025,
      peakMaturityTo: 2055,
      serviceTemp: '17-18°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['italie', 'toscane', 'brunello', 'riserva'],
    },
    {
      name: 'Priorat Les Terrasses',
      producer: 'Álvaro Palacios',
      vintage: 2019,
      region: 'Priorat',
      color: 'red',
      grapeVarieties: ['Grenache', 'Carignan', 'Cabernet Sauvignon'],
      alcoholDegree: 15.0,
      bottleSize: '75cl',
      purchasePrice: 35,
      estimatedValue: 45,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2032,
      serviceTemp: '17-18°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['espagne', 'catalogne', 'puissant'],
    },
    {
      name: 'Rioja Gran Reserva 904',
      producer: 'La Rioja Alta',
      vintage: 2011,
      region: 'Rioja',
      color: 'red',
      grapeVarieties: ['Tempranillo', 'Graciano'],
      alcoholDegree: 13.5,
      bottleSize: '75cl',
      purchasePrice: 55,
      estimatedValue: 75,
      peakMaturityFrom: 2021,
      peakMaturityTo: 2035,
      serviceTemp: '16-17°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['espagne', 'rioja', 'gran reserva', 'tempranillo'],
    },
    {
      name: 'Napa Valley Cabernet Sauvignon',
      producer: 'Opus One',
      vintage: 2018,
      region: 'Napa Valley',
      color: 'red',
      grapeVarieties: ['Cabernet Sauvignon', 'Merlot', 'Cabernet Franc', 'Malbec', 'Petit Verdot'],
      alcoholDegree: 14.5,
      bottleSize: '75cl',
      purchasePrice: 380,
      estimatedValue: 480,
      peakMaturityFrom: 2025,
      peakMaturityTo: 2045,
      serviceTemp: '17-18°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['usa', 'californie', 'napa', 'prestige'],
    },
    {
      name: 'Caymus Special Selection',
      producer: 'Caymus Vineyards',
      vintage: 2019,
      region: 'Napa Valley',
      color: 'red',
      grapeVarieties: ['Cabernet Sauvignon'],
      alcoholDegree: 15.0,
      bottleSize: '75cl',
      purchasePrice: 140,
      estimatedValue: 180,
      peakMaturityFrom: 2024,
      peakMaturityTo: 2038,
      serviceTemp: '17-18°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['usa', 'californie'],
    },
    {
      name: 'Penfolds Grange',
      producer: 'Penfolds',
      vintage: 2017,
      region: 'South Australia',
      color: 'red',
      grapeVarieties: ['Shiraz', 'Cabernet Sauvignon'],
      alcoholDegree: 14.5,
      bottleSize: '75cl',
      purchasePrice: 600,
      estimatedValue: 780,
      peakMaturityFrom: 2027,
      peakMaturityTo: 2050,
      serviceTemp: '17-18°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['australie', 'shiraz', 'icônique', 'prestige'],
    },
    {
      name: 'Saumur-Champigny Les Poyeux',
      producer: 'Domaine des Roches Neuves',
      vintage: 2019,
      region: 'Saumur-Champigny',
      color: 'red',
      grapeVarieties: ['Cabernet Franc'],
      alcoholDegree: 13.0,
      bottleSize: '75cl',
      purchasePrice: 25,
      estimatedValue: 32,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2030,
      serviceTemp: '15-16°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['loire', 'cabernet franc', 'rapport qualité-prix'],
    },
    {
      name: 'Bourgueil Cuvée Amédée',
      producer: 'Domaine de la Chevalerie',
      vintage: 2017,
      region: 'Bourgueil',
      color: 'red',
      grapeVarieties: ['Cabernet Franc'],
      alcoholDegree: 13.0,
      bottleSize: '75cl',
      purchasePrice: 18,
      estimatedValue: 22,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2032,
      serviceTemp: '15-16°C',
      needsAeration: true,
      cellarId: cellarMain,
      tags: ['loire', 'cabernet franc'],
    },
  ];

  // ── VINS BLANCS ───────────────────────────────────────────────────────────────

  const whiteWines = [
    {
      name: 'Montrachet Grand Cru',
      producer: 'Domaine de la Romanée-Conti',
      vintage: 2018,
      region: 'Puligny-Montrachet',
      color: 'white',
      grapeVarieties: ['Chardonnay'],
      alcoholDegree: 14.0,
      bottleSize: '75cl',
      purchasePrice: 4500,
      estimatedValue: 6200,
      peakMaturityFrom: 2026,
      peakMaturityTo: 2045,
      serviceTemp: '12-14°C',
      needsAeration: false,
      cellarId: cellarMain,
      tags: ['grand cru', 'bourgogne', 'chardonnay', 'ultra-prestige'],
    },
    {
      name: 'Meursault Perrières 1er Cru',
      producer: 'Coche-Dury',
      vintage: 2019,
      region: 'Meursault',
      color: 'white',
      grapeVarieties: ['Chardonnay'],
      alcoholDegree: 13.5,
      bottleSize: '75cl',
      purchasePrice: 1200,
      estimatedValue: 1600,
      peakMaturityFrom: 2025,
      peakMaturityTo: 2040,
      serviceTemp: '12-14°C',
      needsAeration: false,
      cellarId: cellarMain,
      tags: ['premier cru', 'bourgogne', 'prestige'],
    },
    {
      name: 'Chassagne-Montrachet Les Caillerets',
      producer: 'Colin-Morey',
      vintage: 2020,
      region: 'Chassagne-Montrachet',
      color: 'white',
      grapeVarieties: ['Chardonnay'],
      alcoholDegree: 13.5,
      bottleSize: '75cl',
      purchasePrice: 120,
      estimatedValue: 160,
      peakMaturityFrom: 2025,
      peakMaturityTo: 2038,
      serviceTemp: '12-14°C',
      cellarId: cellarMain,
      tags: ['premier cru', 'bourgogne'],
    },
    {
      name: 'Chablis Grand Cru Les Clos',
      producer: 'Domaine Raveneau',
      vintage: 2018,
      region: 'Chablis',
      color: 'white',
      grapeVarieties: ['Chardonnay'],
      alcoholDegree: 13.0,
      bottleSize: '75cl',
      purchasePrice: 180,
      estimatedValue: 240,
      peakMaturityFrom: 2024,
      peakMaturityTo: 2038,
      serviceTemp: '11-13°C',
      cellarId: cellarCooler,
      tags: ['grand cru', 'chablis', 'minéral'],
    },
    {
      name: 'Condrieu La Doriane',
      producer: 'Guigal',
      vintage: 2020,
      region: 'Condrieu',
      color: 'white',
      grapeVarieties: ['Viognier'],
      alcoholDegree: 14.0,
      bottleSize: '75cl',
      purchasePrice: 85,
      estimatedValue: 110,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2030,
      serviceTemp: '12-14°C',
      cellarId: cellarCooler,
      tags: ['rhône nord', 'viognier', 'aromatique'],
    },
    {
      name: 'Riesling Clos Sainte-Hune',
      producer: 'Trimbach',
      vintage: 2016,
      region: 'Alsace',
      color: 'white',
      grapeVarieties: ['Riesling'],
      alcoholDegree: 13.0,
      bottleSize: '75cl',
      purchasePrice: 220,
      estimatedValue: 320,
      peakMaturityFrom: 2024,
      peakMaturityTo: 2045,
      serviceTemp: '10-12°C',
      cellarId: cellarMain,
      tags: ['alsace', 'riesling', 'icônique', 'vieillissement'],
    },
    {
      name: 'Riesling Schlossberg Grand Cru',
      producer: 'Marcel Deiss',
      vintage: 2019,
      region: 'Alsace',
      color: 'white',
      grapeVarieties: ['Riesling'],
      alcoholDegree: 12.5,
      bottleSize: '75cl',
      purchasePrice: 55,
      estimatedValue: 70,
      peakMaturityFrom: 2025,
      peakMaturityTo: 2040,
      serviceTemp: '10-12°C',
      cellarId: cellarMain,
      tags: ['alsace', 'grand cru', 'riesling'],
    },
    {
      name: 'Pouilly-Fumé Silex',
      producer: 'Didier Dagueneau',
      vintage: 2020,
      region: 'Pouilly-Fumé',
      color: 'white',
      grapeVarieties: ['Sauvignon Blanc'],
      alcoholDegree: 13.5,
      bottleSize: '75cl',
      purchasePrice: 95,
      estimatedValue: 130,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2032,
      serviceTemp: '11-12°C',
      cellarId: cellarCooler,
      tags: ['loire', 'sauvignon blanc', 'minéral'],
    },
    {
      name: 'Sancerre La Moussière',
      producer: 'Alphonse Mellot',
      vintage: 2021,
      region: 'Sancerre',
      color: 'white',
      grapeVarieties: ['Sauvignon Blanc'],
      alcoholDegree: 13.0,
      bottleSize: '75cl',
      purchasePrice: 28,
      estimatedValue: 35,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2027,
      serviceTemp: '10-12°C',
      cellarId: cellarCooler,
      tags: ['loire', 'sancerre'],
    },
    {
      name: 'Château Haut-Brion Blanc',
      producer: 'Château Haut-Brion',
      vintage: 2017,
      region: 'Pessac-Léognan',
      color: 'white',
      grapeVarieties: ['Sémillon', 'Sauvignon Blanc'],
      alcoholDegree: 13.5,
      bottleSize: '75cl',
      purchasePrice: 1800,
      estimatedValue: 2400,
      peakMaturityFrom: 2025,
      peakMaturityTo: 2045,
      serviceTemp: '13-14°C',
      cellarId: cellarMain,
      tags: ['bordeaux blanc', 'prestige', 'pessac-léognan'],
    },
  ];

  // ── VINS ROSÉS ────────────────────────────────────────────────────────────────

  const rosés = [
    {
      name: 'Bandol Rosé',
      producer: 'Domaine Tempier',
      vintage: 2022,
      region: 'Bandol',
      color: 'rosé',
      grapeVarieties: ['Mourvèdre', 'Grenache', 'Cinsault'],
      alcoholDegree: 13.0,
      bottleSize: '75cl',
      purchasePrice: 38,
      estimatedValue: 48,
      peakMaturityFrom: 2023,
      peakMaturityTo: 2027,
      serviceTemp: '10-12°C',
      cellarId: cellarCooler,
      tags: ['provence', 'rosé', 'bandol'],
    },
    {
      name: 'Palette Rosé Château Simone',
      producer: 'Château Simone',
      vintage: 2021,
      region: 'Palette',
      color: 'rosé',
      grapeVarieties: ['Grenache', 'Mourvèdre', 'Cinsault'],
      alcoholDegree: 13.5,
      bottleSize: '75cl',
      purchasePrice: 42,
      estimatedValue: 55,
      peakMaturityFrom: 2023,
      peakMaturityTo: 2028,
      serviceTemp: '10-12°C',
      cellarId: cellarCooler,
      tags: ['provence', 'rosé', 'gastronomique'],
    },
    {
      name: 'Côtes de Provence Clos Mireille',
      producer: 'Domaines Ott',
      vintage: 2022,
      region: 'Côtes de Provence',
      color: 'rosé',
      grapeVarieties: ['Grenache', 'Cinsault', 'Tibouren'],
      alcoholDegree: 13.0,
      bottleSize: '75cl',
      purchasePrice: 30,
      estimatedValue: 38,
      peakMaturityFrom: 2023,
      peakMaturityTo: 2026,
      serviceTemp: '10-12°C',
      cellarId: cellarCooler,
      tags: ['provence', 'rosé'],
    },
    {
      name: 'Tavel Rosé Domaine de la Mordorée',
      producer: 'Domaine de la Mordorée',
      vintage: 2021,
      region: 'Tavel',
      color: 'rosé',
      grapeVarieties: ['Grenache', 'Cinsault', 'Syrah'],
      alcoholDegree: 14.0,
      bottleSize: '75cl',
      purchasePrice: 22,
      estimatedValue: 28,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2028,
      serviceTemp: '12-14°C',
      cellarId: cellarCooler,
      tags: ['rhône', 'tavel', 'rosé structuré'],
    },
  ];

  // ── VINS ORANGE ───────────────────────────────────────────────────────────────

  const orangeWines = [
    {
      name: 'Ramato',
      producer: 'Radikon',
      vintage: 2018,
      region: 'Frioul',
      color: 'orange',
      grapeVarieties: ['Pinot Grigio'],
      alcoholDegree: 12.5,
      bottleSize: '75cl',
      purchasePrice: 45,
      estimatedValue: 65,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2035,
      serviceTemp: '14-16°C',
      cellarId: cellarMain,
      tags: ['italie', 'orange wine', 'nature', 'macération'],
    },
    {
      name: 'Ribolla Gialla Anfora',
      producer: 'Gravner',
      vintage: 2014,
      region: 'Frioul',
      color: 'orange',
      grapeVarieties: ['Ribolla Gialla'],
      alcoholDegree: 13.0,
      bottleSize: '75cl',
      purchasePrice: 90,
      estimatedValue: 130,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2040,
      serviceTemp: '14-16°C',
      cellarId: cellarMain,
      tags: ['italie', 'orange wine', 'amphore', 'nature'],
    },
    {
      name: 'Rkatsiteli Amber',
      producer: 'Pheasant\'s Tears',
      vintage: 2019,
      region: 'Kakhétie',
      color: 'orange',
      grapeVarieties: ['Rkatsiteli'],
      alcoholDegree: 13.0,
      bottleSize: '75cl',
      purchasePrice: 32,
      estimatedValue: 42,
      peakMaturityFrom: 2021,
      peakMaturityTo: 2030,
      serviceTemp: '14-16°C',
      cellarId: cellarMain,
      tags: ['géorgie', 'orange wine', 'kvevri'],
    },
  ];

  // ── CHAMPAGNES & EFFERVESCENTS ─────────────────────────────────────────────

  const sparklingWines = [
    {
      name: 'Dom Pérignon',
      producer: 'Moët & Chandon',
      category: BottleCategory.sparkling,
      vintage: 2013,
      sparklingType: 'champagne',
      sugarLevel: 'brut',
      region: 'Champagne',
      color: 'white',
      grapeVarieties: ['Chardonnay', 'Pinot Noir'],
      alcoholDegree: 12.5,
      bottleSize: '75cl',
      purchasePrice: 220,
      estimatedValue: 280,
      peakMaturityFrom: 2023,
      peakMaturityTo: 2035,
      serviceTemp: '8-10°C',
      cellarId: cellarCooler,
      tags: ['champagne', 'prestige', 'millésimé'],
    },
    {
      name: 'Krug Grande Cuvée 169ème Édition',
      producer: 'Krug',
      category: BottleCategory.sparkling,
      sparklingType: 'champagne',
      sugarLevel: 'brut',
      region: 'Champagne',
      color: 'white',
      grapeVarieties: ['Pinot Noir', 'Chardonnay', 'Meunier'],
      alcoholDegree: 12.0,
      bottleSize: '75cl',
      purchasePrice: 260,
      estimatedValue: 320,
      peakMaturityFrom: 2023,
      peakMaturityTo: 2032,
      serviceTemp: '8-10°C',
      cellarId: cellarCooler,
      tags: ['champagne', 'prestige', 'non-millésimé', 'assemblage'],
    },
    {
      name: 'Cristal Rosé',
      producer: 'Louis Roederer',
      category: BottleCategory.sparkling,
      vintage: 2014,
      sparklingType: 'champagne',
      sugarLevel: 'brut',
      region: 'Champagne',
      color: 'rosé',
      grapeVarieties: ['Pinot Noir', 'Chardonnay'],
      alcoholDegree: 12.5,
      bottleSize: '75cl',
      purchasePrice: 580,
      estimatedValue: 750,
      peakMaturityFrom: 2024,
      peakMaturityTo: 2040,
      serviceTemp: '8-10°C',
      cellarId: cellarCooler,
      tags: ['champagne', 'rosé', 'prestige', 'millésimé'],
    },
    {
      name: 'Belle Époque',
      producer: 'Perrier-Jouët',
      category: BottleCategory.sparkling,
      vintage: 2014,
      sparklingType: 'champagne',
      sugarLevel: 'brut',
      region: 'Champagne',
      color: 'white',
      grapeVarieties: ['Chardonnay', 'Pinot Noir', 'Meunier'],
      alcoholDegree: 12.5,
      bottleSize: '75cl',
      purchasePrice: 180,
      estimatedValue: 230,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2034,
      serviceTemp: '8-10°C',
      cellarId: cellarCooler,
      tags: ['champagne', 'prestige', 'millésimé', 'élégant'],
    },
    {
      name: 'Salon Le Mesnil',
      producer: 'Salon',
      category: BottleCategory.sparkling,
      vintage: 2008,
      sparklingType: 'champagne',
      sugarLevel: 'brut',
      region: 'Champagne',
      color: 'white',
      grapeVarieties: ['Chardonnay'],
      alcoholDegree: 12.0,
      bottleSize: '75cl',
      purchasePrice: 850,
      estimatedValue: 1200,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2040,
      serviceTemp: '8-10°C',
      cellarId: cellarMain,
      tags: ['champagne', 'blanc de blancs', 'ultra-prestige', 'investissement'],
      notes: 'Le champagne des connaisseurs. Monopole Le Mesnil.',
    },
    {
      name: 'Comtes de Champagne Blanc de Blancs',
      producer: 'Taittinger',
      category: BottleCategory.sparkling,
      vintage: 2012,
      sparklingType: 'champagne',
      sugarLevel: 'brut',
      region: 'Champagne',
      color: 'white',
      grapeVarieties: ['Chardonnay'],
      alcoholDegree: 12.5,
      bottleSize: '75cl',
      purchasePrice: 190,
      estimatedValue: 260,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2038,
      serviceTemp: '8-10°C',
      cellarId: cellarCooler,
      tags: ['champagne', 'blanc de blancs', 'prestige'],
    },
    {
      name: 'Blanc de Blancs Grand Cru',
      producer: 'Pierre Péters',
      category: BottleCategory.sparkling,
      sparklingType: 'champagne',
      sugarLevel: 'extra-brut',
      region: 'Champagne',
      color: 'white',
      grapeVarieties: ['Chardonnay'],
      alcoholDegree: 12.0,
      bottleSize: '75cl',
      purchasePrice: 75,
      estimatedValue: 95,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2030,
      serviceTemp: '8-10°C',
      cellarId: cellarCooler,
      tags: ['champagne', 'blanc de blancs', 'grower', 'extra-brut'],
    },
    {
      name: 'Les Mesmins',
      producer: 'Dhondt-Grellet',
      category: BottleCategory.sparkling,
      sparklingType: 'champagne',
      sugarLevel: 'extra-brut',
      region: 'Champagne',
      color: 'white',
      grapeVarieties: ['Chardonnay'],
      alcoholDegree: 12.5,
      bottleSize: '75cl',
      purchasePrice: 65,
      estimatedValue: 82,
      peakMaturityFrom: 2023,
      peakMaturityTo: 2030,
      serviceTemp: '8-10°C',
      cellarId: cellarCooler,
      tags: ['champagne', 'grower', 'côte des blancs', 'nature'],
    },
    {
      name: 'Millésime Rosé',
      producer: 'Billecart-Salmon',
      category: BottleCategory.sparkling,
      vintage: 2012,
      sparklingType: 'champagne',
      sugarLevel: 'brut',
      region: 'Champagne',
      color: 'rosé',
      grapeVarieties: ['Pinot Noir', 'Chardonnay'],
      alcoholDegree: 12.0,
      bottleSize: '75cl',
      purchasePrice: 230,
      estimatedValue: 310,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2038,
      serviceTemp: '8-10°C',
      cellarId: cellarCooler,
      tags: ['champagne', 'rosé', 'prestige', 'millésimé'],
    },
    {
      name: 'Crémant d\'Alsace Brut',
      producer: 'Dirler-Cadé',
      category: BottleCategory.sparkling,
      sparklingType: 'cremant',
      sugarLevel: 'brut',
      region: 'Alsace',
      color: 'white',
      grapeVarieties: ['Auxerrois', 'Pinot Blanc', 'Pinot Gris'],
      alcoholDegree: 12.0,
      bottleSize: '75cl',
      purchasePrice: 18,
      estimatedValue: 22,
      serviceTemp: '8-10°C',
      cellarId: cellarCooler,
      tags: ['crémant', 'alsace', 'rapport qualité-prix'],
    },
    {
      name: 'Prosecco di Valdobbiadene Superiore DOCG',
      producer: 'Bisol',
      category: BottleCategory.sparkling,
      sparklingType: 'prosecco',
      sugarLevel: 'extra-sec',
      region: 'Valdobbiadene',
      color: 'white',
      grapeVarieties: ['Glera'],
      alcoholDegree: 11.5,
      bottleSize: '75cl',
      purchasePrice: 22,
      estimatedValue: 28,
      serviceTemp: '7-9°C',
      cellarId: cellarCooler,
      tags: ['prosecco', 'italie', 'vénétie'],
    },
    {
      name: 'Cava Gran Reserva',
      producer: 'Gramona',
      category: BottleCategory.sparkling,
      vintage: 2017,
      sparklingType: 'cava',
      sugarLevel: 'brut',
      region: 'Penedès',
      color: 'white',
      grapeVarieties: ['Xarel·lo', 'Macabeo', 'Parellada'],
      alcoholDegree: 12.5,
      bottleSize: '75cl',
      purchasePrice: 35,
      estimatedValue: 45,
      peakMaturityFrom: 2022,
      peakMaturityTo: 2030,
      serviceTemp: '8-10°C',
      cellarId: cellarCooler,
      tags: ['cava', 'espagne', 'gran reserva'],
    },
    {
      name: 'Pétillant Naturel Poiré',
      producer: 'Domaine de la Garrelière',
      category: BottleCategory.sparkling,
      sparklingType: 'petnat',
      sugarLevel: 'brut',
      region: 'Loire',
      color: 'white',
      grapeVarieties: ['Poiré'],
      alcoholDegree: 7.0,
      bottleSize: '75cl',
      purchasePrice: 14,
      estimatedValue: 18,
      serviceTemp: '8-10°C',
      cellarId: cellarCooler,
      tags: ['pétnat', 'nature', 'poiré', 'curiosité'],
    },
    {
      name: 'Champagne Blanc de Noirs Vieilles Vignes',
      producer: 'Egly-Ouriet',
      category: BottleCategory.sparkling,
      sparklingType: 'champagne',
      sugarLevel: 'extra-brut',
      region: 'Champagne',
      color: 'white',
      grapeVarieties: ['Pinot Noir'],
      alcoholDegree: 12.5,
      bottleSize: '75cl',
      purchasePrice: 130,
      estimatedValue: 175,
      peakMaturityFrom: 2023,
      peakMaturityTo: 2033,
      serviceTemp: '8-10°C',
      cellarId: cellarCooler,
      tags: ['champagne', 'blanc de noirs', 'grower', 'vieilles vignes'],
    },
    {
      name: 'La Grande Dame',
      producer: 'Veuve Clicquot',
      category: BottleCategory.sparkling,
      vintage: 2015,
      sparklingType: 'champagne',
      sugarLevel: 'brut',
      region: 'Champagne',
      color: 'white',
      grapeVarieties: ['Pinot Noir', 'Chardonnay'],
      alcoholDegree: 12.5,
      bottleSize: 'Magnum 150cl',
      purchasePrice: 480,
      estimatedValue: 600,
      peakMaturityFrom: 2024,
      peakMaturityTo: 2038,
      serviceTemp: '8-10°C',
      cellarId: cellarMain,
      tags: ['champagne', 'prestige', 'magnum', 'cadeau'],
    },
  ];

  // ── SPIRITUEUX ────────────────────────────────────────────────────────────────

  const spirits = [
    {
      name: 'Macallan 25 ans Sherry Oak',
      producer: 'The Macallan',
      spiritType: 'whisky',
      edition: 'Sherry Oak',
      declaredAge: 25,
      alcoholDegree: 43.0,
      bottleSize: '70cl',
      caskType: 'Sherry Oloroso',
      purchasePrice: 2200,
      estimatedValue: 3200,
      region: 'Speyside',
      tags: ['whisky', 'écossais', 'single malt', 'prestige', 'sherry'],
      cellarId: cellarShelf,
      aromaticProfile: 'Riche, fruité, épices douces. Notes de fruits secs, chocolat noir.',
    },
    {
      name: 'Macallan 18 ans Sherry Oak',
      producer: 'The Macallan',
      spiritType: 'whisky',
      edition: 'Sherry Oak',
      declaredAge: 18,
      alcoholDegree: 43.0,
      bottleSize: '70cl',
      caskType: 'Sherry Oloroso',
      purchasePrice: 380,
      estimatedValue: 520,
      region: 'Speyside',
      tags: ['whisky', 'écossais', 'single malt', 'sherry'],
      cellarId: cellarShelf,
    },
    {
      name: 'Lagavulin 16 ans',
      producer: 'Lagavulin',
      spiritType: 'whisky',
      declaredAge: 16,
      alcoholDegree: 43.0,
      bottleSize: '70cl',
      caskType: 'Ex-Bourbon',
      purchasePrice: 75,
      estimatedValue: 95,
      region: 'Islay',
      tags: ['whisky', 'écossais', 'single malt', 'tourbé', 'islay'],
      cellarId: cellarShelf,
      aromaticProfile: 'Fumé, tourbé, iodé. Long finish maritime.',
    },
    {
      name: 'Laphroaig 10 ans Cask Strength',
      producer: 'Laphroaig',
      spiritType: 'whisky',
      declaredAge: 10,
      alcoholDegree: 57.8,
      bottleSize: '70cl',
      caskType: 'Ex-Bourbon',
      purchasePrice: 72,
      estimatedValue: 90,
      region: 'Islay',
      tags: ['whisky', 'écossais', 'tourbé', 'cask strength', 'islay'],
      cellarId: cellarShelf,
    },
    {
      name: 'Glenfarclas 105',
      producer: 'Glenfarclas',
      spiritType: 'whisky',
      alcoholDegree: 60.0,
      bottleSize: '70cl',
      caskType: 'Sherry Butt',
      purchasePrice: 65,
      estimatedValue: 80,
      region: 'Speyside',
      tags: ['whisky', 'écossais', 'cask strength', 'sherry'],
      cellarId: cellarShelf,
    },
    {
      name: 'Springbank 15 ans',
      producer: 'Springbank',
      spiritType: 'whisky',
      declaredAge: 15,
      alcoholDegree: 46.0,
      bottleSize: '70cl',
      caskType: 'Ex-Bourbon / Ex-Sherry',
      purchasePrice: 120,
      estimatedValue: 180,
      region: 'Campbeltown',
      tags: ['whisky', 'écossais', 'campbeltown', 'artisanal'],
      cellarId: cellarShelf,
    },
    {
      name: 'Buffalo Trace Antique Collection George T. Stagg',
      producer: 'Buffalo Trace',
      spiritType: 'whisky',
      edition: 'Antique Collection',
      alcoholDegree: 64.1,
      bottleSize: '75cl',
      caskType: 'New Charred Oak',
      purchasePrice: 350,
      estimatedValue: 600,
      region: 'Kentucky',
      tags: ['bourbon', 'usa', 'kentucky', 'cask strength', 'collector'],
      cellarId: cellarShelf,
    },
    {
      name: 'Pappy Van Winkle 20 ans',
      producer: 'Old Rip Van Winkle',
      spiritType: 'whisky',
      declaredAge: 20,
      alcoholDegree: 45.2,
      bottleSize: '75cl',
      caskType: 'New Charred Oak',
      purchasePrice: 2500,
      estimatedValue: 4000,
      region: 'Kentucky',
      tags: ['bourbon', 'usa', 'kentucky', 'ultra-rare', 'investissement'],
      cellarId: cellarShelf,
      notes: 'Extrêmement rare. L\'un des bourbons les plus recherchés au monde.',
    },
    {
      name: 'Yamazaki 18 ans',
      producer: 'Suntory',
      spiritType: 'whisky',
      declaredAge: 18,
      alcoholDegree: 43.0,
      bottleSize: '70cl',
      caskType: 'Mizunara Oak / Sherry / Bourbon',
      purchasePrice: 450,
      estimatedValue: 700,
      region: 'Osaka',
      tags: ['whisky', 'japonais', 'suntory', 'prestige'],
      cellarId: cellarShelf,
      aromaticProfile: 'Complexe, boisé, épicé. Notes de sandalwood et fruits confits.',
    },
    {
      name: 'Nikka From The Barrel',
      producer: 'Nikka',
      spiritType: 'whisky',
      alcoholDegree: 51.4,
      bottleSize: '50cl',
      caskType: 'Bourbon / Sherry',
      purchasePrice: 50,
      estimatedValue: 65,
      region: 'Hokkaido',
      tags: ['whisky', 'japonais', 'nikka', 'rapport qualité-prix'],
      cellarId: cellarShelf,
    },
    {
      name: 'Rhum Vieux Agricole XO',
      producer: 'Rhum J.M',
      spiritType: 'rhum',
      edition: 'XO',
      declaredAge: 6,
      alcoholDegree: 45.0,
      bottleSize: '70cl',
      caskType: 'Ex-Bourbon',
      purchasePrice: 95,
      estimatedValue: 120,
      region: 'Martinique',
      tags: ['rhum', 'martinique', 'agricole', 'xo', 'aoc'],
      cellarId: cellarShelf,
      aromaticProfile: 'Canne fraîche, vanille, épices créoles, bois.',
    },
    {
      name: 'Appleton Estate 21 ans Nassau Valley',
      producer: 'Appleton Estate',
      spiritType: 'rhum',
      declaredAge: 21,
      alcoholDegree: 43.0,
      bottleSize: '70cl',
      caskType: 'Ex-Bourbon / Ex-Sherry',
      purchasePrice: 180,
      estimatedValue: 240,
      region: 'Jamaïque',
      tags: ['rhum', 'jamaïque', 'vieux', 'prestige'],
      cellarId: cellarShelf,
    },
    {
      name: 'Barbancourt Réserve du Domaine 15 ans',
      producer: 'Barbancourt',
      spiritType: 'rhum',
      declaredAge: 15,
      alcoholDegree: 43.0,
      bottleSize: '70cl',
      caskType: 'Chêne français',
      purchasePrice: 70,
      estimatedValue: 90,
      region: 'Haïti',
      tags: ['rhum', 'haïti', 'vieux', 'agricole'],
      cellarId: cellarShelf,
    },
    {
      name: 'Diplomatico Reserva Exclusiva',
      producer: 'Diplomatico',
      spiritType: 'rhum',
      declaredAge: 12,
      alcoholDegree: 40.0,
      bottleSize: '70cl',
      caskType: 'Ex-Bourbon',
      purchasePrice: 42,
      estimatedValue: 52,
      region: 'Venezuela',
      tags: ['rhum', 'venezuela', 'moelleux'],
      cellarId: cellarShelf,
    },
    {
      name: 'Hendrick\'s Gin',
      producer: 'William Grant & Sons',
      spiritType: 'gin',
      alcoholDegree: 41.4,
      bottleSize: '70cl',
      purchasePrice: 42,
      estimatedValue: 48,
      region: 'Écosse',
      tags: ['gin', 'écossais', 'concombre rose'],
      cellarId: cellarShelf,
      additions: 'Concombre, pétales de rose',
    },
    {
      name: 'Monkey 47 Schwarzwald Dry Gin',
      producer: 'Monkey 47',
      spiritType: 'gin',
      alcoholDegree: 47.0,
      bottleSize: '50cl',
      purchasePrice: 48,
      estimatedValue: 60,
      region: 'Forêt Noire',
      tags: ['gin', 'allemagne', 'premium', '47 botaniques'],
      cellarId: cellarShelf,
    },
    {
      name: 'Cognac Louis XIII',
      producer: 'Rémy Martin',
      spiritType: 'cognac',
      alcoholDegree: 40.0,
      bottleSize: '70cl',
      caskType: 'Limousin Oak',
      purchasePrice: 4200,
      estimatedValue: 5800,
      region: 'Cognac',
      tags: ['cognac', 'prestige', 'ultra-prestige', 'investissement'],
      cellarId: cellarShelf,
      notes: 'Assemblage de plus de 1200 eaux-de-vie de grande Champagne.',
    },
    {
      name: 'Cognac XO Excellence',
      producer: 'Hennessy',
      spiritType: 'cognac',
      edition: 'XO',
      alcoholDegree: 40.0,
      bottleSize: '70cl',
      caskType: 'Limousin Oak',
      purchasePrice: 180,
      estimatedValue: 230,
      region: 'Cognac',
      tags: ['cognac', 'xo', 'prestige'],
      cellarId: cellarShelf,
    },
    {
      name: 'Armagnac Château de Pellehaut 1982',
      producer: 'Château de Pellehaut',
      spiritType: 'armagnac',
      vintage: 1982,
      alcoholDegree: 48.0,
      bottleSize: '70cl',
      caskType: 'Chêne de Gascogne',
      purchasePrice: 320,
      estimatedValue: 480,
      region: 'Bas-Armagnac',
      tags: ['armagnac', 'millésimé', 'vieux', 'rare'],
      cellarId: cellarShelf,
    },
    {
      name: 'Calvados Pays d\'Auge XO',
      producer: 'Château du Breuil',
      spiritType: 'calvados',
      edition: 'XO',
      alcoholDegree: 40.0,
      bottleSize: '70cl',
      caskType: 'Chêne français',
      purchasePrice: 85,
      estimatedValue: 110,
      region: 'Pays d\'Auge',
      tags: ['calvados', 'normandie', 'pomme', 'xo'],
      cellarId: cellarShelf,
    },
    {
      name: 'Mezcal Vago Ensamble en Barro',
      producer: 'Mezcal Vago',
      spiritType: 'mezcal',
      alcoholDegree: 51.5,
      bottleSize: '70cl',
      purchasePrice: 75,
      estimatedValue: 95,
      region: 'Oaxaca',
      tags: ['mezcal', 'mexique', 'artisanal', 'barro', 'terroir'],
      cellarId: cellarShelf,
      additions: 'Distillé en pot d\'argile',
    },
    {
      name: 'Tequila Don Julio 1942',
      producer: 'Don Julio',
      spiritType: 'tequila',
      alcoholDegree: 38.0,
      bottleSize: '70cl',
      caskType: 'Chêne américain',
      purchasePrice: 120,
      estimatedValue: 150,
      region: 'Jalisco',
      tags: ['tequila', 'mexique', 'añejo', 'prestige'],
      cellarId: cellarShelf,
    },
    {
      name: 'Absinthe Verte de Pontarlier',
      producer: 'Distillerie Guy',
      spiritType: 'absinthe',
      alcoholDegree: 65.0,
      bottleSize: '70cl',
      purchasePrice: 38,
      estimatedValue: 48,
      region: 'Jura',
      tags: ['absinthe', 'france', 'pontarlier', 'artisanal'],
      cellarId: cellarShelf,
    },
    {
      name: 'Eau-de-vie de Poire Williams',
      producer: 'Massenez',
      spiritType: 'eau-de-vie',
      alcoholDegree: 45.0,
      bottleSize: '70cl',
      purchasePrice: 45,
      estimatedValue: 55,
      region: 'Alsace',
      tags: ['eau-de-vie', 'alsace', 'artisanal', 'poire williams'],
      cellarId: cellarShelf,
    },
  ];

  // ── CIGARES ───────────────────────────────────────────────────────────────────

  const cigars = [
    {
      name: 'Cohiba Behike BHK 52',
      producer: 'Habanos S.A.',
      format: 'Beli­coso',
      quantity: 10,
      leafOrigin: 'Cuba',
      manufactureYear: 2022,
      recommendedHumidity: 65,
      humidificationSystem: 'Humidificateur boveda 65%',
      purchasePrice: 750,
      estimatedValue: 950,
      tags: ['cubain', 'cohiba', 'prestige', 'bhk'],
      cellarId: cellarShelf,
      notes: 'Le summum de la production Cohiba. Envoltura Medio Tiempo.',
    },
    {
      name: 'Cohiba Esplendidos',
      producer: 'Habanos S.A.',
      format: 'Churchill',
      quantity: 25,
      leafOrigin: 'Cuba',
      manufactureYear: 2021,
      recommendedHumidity: 65,
      humidificationSystem: 'Boveda 65%',
      purchasePrice: 1200,
      estimatedValue: 1500,
      tags: ['cubain', 'cohiba', 'churchill', 'prestige'],
      cellarId: cellarShelf,
    },
    {
      name: 'Montecristo No. 2',
      producer: 'Habanos S.A.',
      format: 'Torpedo',
      quantity: 25,
      leafOrigin: 'Cuba',
      manufactureYear: 2022,
      recommendedHumidity: 65,
      humidificationSystem: 'Boveda 65%',
      purchasePrice: 580,
      estimatedValue: 720,
      tags: ['cubain', 'montecristo', 'torpedo', 'icônique'],
      cellarId: cellarShelf,
    },
    {
      name: 'Romeo y Julieta Wide Churchill',
      producer: 'Habanos S.A.',
      format: 'Wide Churchill',
      quantity: 25,
      leafOrigin: 'Cuba',
      manufactureYear: 2021,
      recommendedHumidity: 65,
      humidificationSystem: 'Boveda 65%',
      purchasePrice: 520,
      estimatedValue: 650,
      tags: ['cubain', 'romeo y julieta', 'churchill'],
      cellarId: cellarShelf,
    },
    {
      name: 'Partagás Serie D No. 4',
      producer: 'Habanos S.A.',
      format: 'Robusto',
      quantity: 25,
      leafOrigin: 'Cuba',
      manufactureYear: 2022,
      recommendedHumidity: 65,
      humidificationSystem: 'Boveda 65%',
      purchasePrice: 460,
      estimatedValue: 580,
      tags: ['cubain', 'partagás', 'robusto'],
      cellarId: cellarShelf,
      notes: 'Très populaire, goût riche et terreux.',
    },
    {
      name: 'H. Upmann Magnum 54',
      producer: 'Habanos S.A.',
      format: 'Toro',
      quantity: 25,
      leafOrigin: 'Cuba',
      manufactureYear: 2021,
      recommendedHumidity: 65,
      humidificationSystem: 'Boveda 65%',
      purchasePrice: 540,
      estimatedValue: 680,
      tags: ['cubain', 'h. upmann', 'toro'],
      cellarId: cellarShelf,
    },
    {
      name: 'Arturo Fuente Opus X BBMF',
      producer: 'Arturo Fuente',
      format: 'Double Corona',
      quantity: 5,
      leafOrigin: 'République Dominicaine',
      manufactureYear: 2022,
      recommendedHumidity: 67,
      humidificationSystem: 'Boveda 69%',
      purchasePrice: 380,
      estimatedValue: 550,
      tags: ['dominicain', 'opus x', 'prestige', 'collector'],
      cellarId: cellarShelf,
      notes: 'Opus X est le seul cigare dominicain cultivé entièrement sur place.',
    },
    {
      name: 'Padron 1926 Serie No. 1',
      producer: 'Padron',
      format: 'Figurado',
      quantity: 10,
      leafOrigin: 'Nicaragua',
      manufactureYear: 2022,
      recommendedHumidity: 68,
      humidificationSystem: 'Boveda 69%',
      purchasePrice: 420,
      estimatedValue: 520,
      tags: ['nicaraguayen', 'padron', '1926', 'prestige'],
      cellarId: cellarShelf,
    },
    {
      name: 'Liga Privada No. 9',
      producer: 'Drew Estate',
      format: 'Toro',
      quantity: 24,
      leafOrigin: 'Nicaragua',
      manufactureYear: 2023,
      recommendedHumidity: 68,
      humidificationSystem: 'Boveda 69%',
      purchasePrice: 320,
      estimatedValue: 400,
      tags: ['nicaraguayen', 'liga privada', 'maduro'],
      cellarId: cellarShelf,
    },
    {
      name: 'Davidoff Winston Churchill The Late Hour',
      producer: 'Davidoff',
      format: 'Robusto',
      quantity: 20,
      leafOrigin: 'République Dominicaine',
      manufactureYear: 2022,
      recommendedHumidity: 65,
      humidificationSystem: 'Boveda 65%',
      purchasePrice: 480,
      estimatedValue: 600,
      tags: ['dominicain', 'davidoff', 'prestige', 'winston churchill'],
      cellarId: cellarShelf,
    },
    {
      name: 'Hoyo de Monterrey Épicure No. 2',
      producer: 'Habanos S.A.',
      format: 'Robusto',
      quantity: 25,
      leafOrigin: 'Cuba',
      manufactureYear: 2022,
      recommendedHumidity: 65,
      humidificationSystem: 'Boveda 65%',
      purchasePrice: 450,
      estimatedValue: 560,
      tags: ['cubain', 'hoyo de monterrey', 'robusto', 'doux'],
      cellarId: cellarShelf,
    },
    {
      name: 'Bolivar Belicosos Finos',
      producer: 'Habanos S.A.',
      format: 'Belicoso',
      quantity: 25,
      leafOrigin: 'Cuba',
      manufactureYear: 2021,
      recommendedHumidity: 65,
      humidificationSystem: 'Boveda 65%',
      purchasePrice: 420,
      estimatedValue: 540,
      tags: ['cubain', 'bolivar', 'belicoso', 'fort'],
      cellarId: cellarShelf,
    },
  ];

  // ─── Insert all inventory items ───────────────────────────────────────────────

  console.log('  Creating wines...');
  const allWines = [...redWines, ...whiteWines, ...rosés, ...orangeWines];
  const createdWines: string[] = [];
  for (const wine of allWines) {
    const { cellarId, tags, ...rest } = wine as any;
    const item = await prisma.inventoryItem.create({
      data: {
        userId: admin.id,
        cellarId,
        category: BottleCategory.wine,
        tags: tags ?? [],
        ...rest,
      },
    });
    createdWines.push(item.id);
  }

  console.log('  Creating sparkling...');
  const createdSparkling: string[] = [];
  for (const sp of sparklingWines) {
    const { cellarId, tags, category: _cat, ...rest } = sp as any;
    const item = await prisma.inventoryItem.create({
      data: {
        userId: admin.id,
        cellarId,
        category: BottleCategory.sparkling,
        tags: tags ?? [],
        ...rest,
      },
    });
    createdSparkling.push(item.id);
  }

  console.log('  Creating spirits...');
  const createdSpirits: string[] = [];
  for (const sp of spirits) {
    const { cellarId, tags, vintage, ...rest } = sp as any;
    const item = await prisma.inventoryItem.create({
      data: {
        userId: admin.id,
        cellarId,
        category: BottleCategory.spirit,
        tags: tags ?? [],
        ...(vintage ? { vintage } : {}),
        ...rest,
      },
    });
    createdSpirits.push(item.id);
  }

  console.log('  Creating cigars...');
  const createdCigars: string[] = [];
  for (const ci of cigars) {
    const { cellarId, tags, ...rest } = ci as any;
    const item = await prisma.inventoryItem.create({
      data: {
        userId: admin.id,
        cellarId,
        category: BottleCategory.cigar,
        tags: tags ?? [],
        ...rest,
      },
    });
    createdCigars.push(item.id);
  }

  // ─── Demo user items ──────────────────────────────────────────────────────────

  console.log('  Creating demo user items...');
  await prisma.inventoryItem.createMany({
    data: [
      {
        userId: user.id,
        cellarId: cellars[4].id,
        category: BottleCategory.wine,
        name: 'Crozes-Hermitage',
        producer: 'Delas Frères',
        vintage: 2020,
        color: 'red',
        grapeVarieties: ['Syrah'],
        alcoholDegree: 13.5,
        bottleSize: '75cl',
        purchasePrice: 18,
        region: 'Crozes-Hermitage',
        tags: ['rhône', 'syrah'],
        peakMaturityFrom: 2023,
        peakMaturityTo: 2028,
        serviceTemp: '16-17°C',
      },
      {
        userId: user.id,
        cellarId: cellars[4].id,
        category: BottleCategory.sparkling,
        name: 'Champagne Brut Rosé',
        producer: 'Nicolas Feuillatte',
        sparklingType: 'champagne',
        sugarLevel: 'brut',
        color: 'rosé',
        grapeVarieties: ['Pinot Noir', 'Chardonnay'],
        alcoholDegree: 12.0,
        bottleSize: '75cl',
        purchasePrice: 38,
        region: 'Champagne',
        tags: ['champagne', 'rosé'],
        serviceTemp: '8-10°C',
      },
      {
        userId: user.id,
        cellarId: cellars[4].id,
        category: BottleCategory.spirit,
        name: 'Oban 14 ans',
        producer: 'Oban',
        spiritType: 'whisky',
        declaredAge: 14,
        alcoholDegree: 43.0,
        bottleSize: '70cl',
        caskType: 'Ex-Bourbon',
        region: 'Highlands',
        tags: ['whisky', 'écossais', 'highlands'],
        purchasePrice: 65,
      },
      {
        userId: user.id,
        cellarId: cellars[4].id,
        category: BottleCategory.wine,
        name: 'Sancerre Blanc',
        producer: 'Henri Bourgeois',
        vintage: 2021,
        color: 'white',
        grapeVarieties: ['Sauvignon Blanc'],
        alcoholDegree: 13.0,
        bottleSize: '75cl',
        purchasePrice: 22,
        region: 'Sancerre',
        tags: ['loire', 'sancerre'],
        peakMaturityFrom: 2022,
        peakMaturityTo: 2026,
        serviceTemp: '10-12°C',
      },
      {
        userId: user.id,
        cellarId: cellars[4].id,
        category: BottleCategory.cigar,
        name: 'Romeo y Julieta No. 3',
        producer: 'Habanos S.A.',
        format: 'Corona',
        quantity: 25,
        leafOrigin: 'Cuba',
        recommendedHumidity: 65,
        humidificationSystem: 'Boveda 65%',
        purchasePrice: 320,
        tags: ['cubain', 'romeo y julieta', 'corona'],
      },
    ],
  });

  // ─── Assign items to collections ──────────────────────────────────────────────

  console.log('  Assigning collections...');

  // Investissement: vins très chers + spiritueux premium
  const investissementItems = [
    createdWines[0], // Château Pétrus
    createdWines[1], // Château Margaux
    createdWines[4], // Romanée-Conti
    createdWines[7], // Hermitage La Chapelle
    createdWines[17], // Penfolds Grange
    createdSparkling[4], // Salon Le Mesnil
    createdSpirits[0], // Macallan 25
    createdSpirits[7], // Pappy Van Winkle
    createdSpirits[16], // Cognac Louis XIII
    createdCigars[0], // Cohiba Behike
  ];

  await prisma.collection.update({
    where: { id: colInvestissement.id },
    data: { items: { connect: investissementItems.map((id) => ({ id })) } },
  });

  // Cadeaux reçus
  const cadeauxItems = [
    createdSparkling[14], // La Grande Dame Magnum
    createdSpirits[8], // Yamazaki 18
    createdCigars[6], // Arturo Fuente Opus X
  ];
  await prisma.collection.update({
    where: { id: colCadeaux.id },
    data: { items: { connect: cadeauxItems.map((id) => ({ id })) } },
  });

  // Coups de coeur
  const coupsItems = [
    createdWines[5], // Gevrey-Chambertin Clos Saint-Jacques
    createdWines[6], // Chambolle-Musigny Les Amoureuses
    createdWines[10], // Châteauneuf-du-Pape Rayas
    createdSparkling[1], // Krug Grande Cuvée
    createdSpirits[2], // Lagavulin 16
    createdSpirits[5], // Springbank 15
  ];
  await prisma.collection.update({
    where: { id: colCoups.id },
    data: { items: { connect: coupsItems.map((id) => ({ id })) } },
  });

  // Club dégustation
  const dégustationItems = [
    createdWines[11], // Barolo Brunate
    createdWines[12], // Brunello di Montalcino
    createdWines[20], // Orange wine Ramato
    createdWines[21], // Ribolla Gialla
    createdSparkling[6], // Pierre Péters
    createdSparkling[7], // Dhondt-Grellet
    createdSpirits[10], // Rhum J.M XO
    createdSpirits[14], // Hendrick's
  ];
  await prisma.collection.update({
    where: { id: colDegustation.id },
    data: { items: { connect: dégustationItems.map((id) => ({ id })) } },
  });

  // Fêtes
  const fêtesItems = [
    createdSparkling[0], // Dom Pérignon
    createdSparkling[2], // Cristal Rosé
    createdSparkling[3], // Belle Époque
    createdSparkling[14], // La Grande Dame Magnum
    createdCigars[2], // Montecristo No. 2
    createdCigars[4], // Partagás Serie D
  ];
  await prisma.collection.update({
    where: { id: colFetes.id },
    data: { items: { connect: fêtesItems.map((id) => ({ id })) } },
  });

  // ─── Tasting Notes ────────────────────────────────────────────────────────────

  console.log('  Creating tasting notes...');

  await prisma.tastingNote.createMany({
    data: [
      {
        userId: admin.id,
        itemId: createdWines[0],
        tastedAt: new Date('2024-12-31'),
        context: 'Réveillon du Nouvel An en famille',
        rating: 98,
        notes: 'Époustouflant. Truffe noire, cassis, cuir fin. Tanins de velours pur. Finish interminable, plus de 90 secondes. Un monument de Pomerol.',
        foodPairing: 'Filet de bœuf Wellington, truffe noire',
      },
      {
        userId: admin.id,
        itemId: createdWines[4],
        tastedAt: new Date('2024-06-15'),
        context: 'Anniversaire de mariage — ouverture spéciale',
        rating: 100,
        notes: 'La perfection incarnée. Impossible à décrire dans sa totalité. Chaque gorgée révèle une nouvelle dimension. Pinot Noir transcendé au-delà du possible.',
        foodPairing: 'Sole meunière au beurre noisette',
      },
      {
        userId: admin.id,
        itemId: createdWines[5],
        tastedAt: new Date('2024-09-20'),
        context: 'Dîner avec des amis sommeliers',
        rating: 95,
        notes: 'Superbe expression du Clos Saint-Jacques. Fruits rouges intenses, sous-bois, épices. Grande persistance aromatique. Rousseau au sommet.',
        foodPairing: 'Pintade aux morilles, pommes sarladaises',
      },
      {
        userId: admin.id,
        itemId: createdSparkling[0],
        tastedAt: new Date('2024-01-01'),
        context: 'Minuit du Nouvel An',
        rating: 96,
        notes: 'Dom Pérignon 2013 au sommet de sa forme. Toast brioché, agrumes confits, craie. Bulles fines et persistantes. Longueur exceptionnelle.',
        foodPairing: 'Huîtres Gillardeau, caviar Osciètre',
      },
      {
        userId: admin.id,
        itemId: createdSparkling[4],
        tastedAt: new Date('2023-12-25'),
        context: 'Noël en famille — bouteille de légende',
        rating: 99,
        notes: 'Salon 2008 à maturité parfaite. Craie blanche, citron confit, miel d\'acacia, beurre noisette. La tension et la minéralité sont extraordinaires.',
        foodPairing: 'Homard à la nage, beurre blanc',
      },
      {
        userId: admin.id,
        itemId: createdSpirits[0],
        tastedAt: new Date('2024-03-10'),
        context: 'Soirée dégustation privée',
        rating: 97,
        notes: 'Macallan 25 Sherry Oak — opulence absolue. Fruits secs, épices orientales, chocolat noir, cuir. Finish infini sur la noix et la cannelle.',
        foodPairing: 'Plateau de fromages affinés',
      },
      {
        userId: admin.id,
        itemId: createdSpirits[2],
        tastedAt: new Date('2024-07-04'),
        context: 'Soirée d\'été sur la terrasse',
        rating: 92,
        notes: 'Lagavulin 16 — emblématique. Fumée, tourbe, iode. Corps plein et onctueux. Quelques gouttes d\'eau libèrent des notes de café et de cacao.',
        foodPairing: 'Saumon fumé d\'Écosse',
      },
      {
        userId: admin.id,
        itemId: createdCigars[0],
        tastedAt: new Date('2024-05-01'),
        context: 'Après dîner gastronomique',
        rating: 99,
        notes: 'Cohiba Behike BHK 52 — l\'apex de la production cubaine. Construction parfaite, tirage exemplaire. Notes de chocolat noir, café espresso, cèdre, épices douces. Combustion parfaite tout du long.',
        foodPairing: 'Verre de Macallan 18 ans',
      },
      {
        userId: admin.id,
        itemId: createdWines[11],
        tastedAt: new Date('2024-10-05'),
        context: 'Verticale Barolo avec des amis italiens',
        rating: 94,
        notes: 'Barolo Brunate 2016 — Nebbiolo majestueux. Rose fanée, goudron, cerises noires, réglisse. Tanins fermes mais enrobés. Très long avenir.',
        foodPairing: 'Tajarin au beurre et truffe blanche d\'Alba',
      },
      {
        userId: admin.id,
        itemId: createdWines[8],
        tastedAt: new Date('2024-02-14'),
        context: 'Saint-Valentin — dîner romantique',
        rating: 93,
        notes: 'Hermitage La Chapelle 2012 enfin à maturité. Olive noire, viande fumée, violette, fruits noirs. Tanins fondus. Grande complexité du millésime.',
        foodPairing: 'Gigot d\'agneau aux herbes de Provence',
      },
      {
        userId: user.id,
        itemId: null,
        tastedAt: new Date('2024-11-15'),
        context: 'Dégustation blind avec des amis',
        rating: 88,
        notes: 'Vin rouge non identifié — devine un Bordeaux. Fruits noirs, cassis, pointe boisée. Bonne longueur. Tanins présents mais agréables.',
      },
      {
        userId: admin.id,
        itemId: createdSpirits[8],
        tastedAt: new Date('2024-04-20'),
        context: 'Découverte des whiskies japonais',
        rating: 95,
        notes: 'Yamazaki 18 — voyage gustatif unique. Bois de santal, fruits exotiques, épices japonaises, fleurs de cerisier. La magie du fût Mizunara.',
        foodPairing: 'Dark chocolate 85%, noix du Brésil',
      },
    ],
  });

  // ─── Summary ──────────────────────────────────────────────────────────────────

  const counts = {
    wines: createdWines.length,
    sparkling: createdSparkling.length,
    spirits: createdSpirits.length,
    cigars: createdCigars.length,
  };

  console.log('\n✅ Seeding complete!');
  console.log(`   Users         : 2`);
  console.log(`   Cellars       : ${cellars.length}`);
  console.log(`   Collections   : 5`);
  console.log(`   Wines         : ${counts.wines}`);
  console.log(`   Sparkling     : ${counts.sparkling}`);
  console.log(`   Spirits       : ${counts.spirits}`);
  console.log(`   Cigars        : ${counts.cigars}`);
  console.log(`   Total items   : ${counts.wines + counts.sparkling + counts.spirits + counts.cigars + 5}`);
  console.log(`   Tasting notes : 12`);
  console.log(`\n   admin@glou.app / Demo1234!demo`);
  console.log(`   demo@glou.app  / Demo1234!demo`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
