# GoReleaser v2 configuration for building and publishing glou-server binaries
version: 2

project_name: glou-server

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - id: glou
    main: ./cmd/api
    binary: glou-server
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

snapshot:
  name_template: "{{ incpatch .Version }}-next"

brews:
  - repository:
      owner: jackthomasanderson
      name: homebrew-tap
    description: "Self-hosted wine cellar manager"
    homepage: "https://github.com/jackthomasanderson/glou-server"
    license: MIT

# Docker builds are handled by the separate docker-release job in GitHub Actions
# dockers:
#   - image_templates:
#       - "ghcr.io/jackthomasanderson/glou-server:{{ .Version }}"
#       - "ghcr.io/jackthomasanderson/glou-server:latest"
