#!/usr/bin/env node
// Regenerates THIRD_PARTY_NOTICES.md from the production dependency trees of
// api/ and web/ (what ends up in the Docker images). Run `npm ci` in both first:
//   node scripts/generate-notices.mjs
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function licenseOf(pkg) {
  const l = pkg.license ?? pkg.licenses;
  if (!l) return 'UNKNOWN';
  if (typeof l === 'string') return l;
  if (Array.isArray(l)) return l.map((x) => x.type ?? x).join(' OR ');
  return l.type ?? 'UNKNOWN';
}

function repoOf(pkg) {
  const r = typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url;
  return r ? r.replace(/^git\+/, '').replace(/\.git$/, '').replace(/^git:\/\//, 'https://') : (pkg.homepage ?? '');
}

function collect(app) {
  const dir = join(root, app);
  if (!existsSync(join(dir, 'node_modules'))) throw new Error(`${app}/node_modules missing: run npm ci first`);
  // `npm ls` exits 1 on peer-dependency noise yet still prints the tree.
  let listing;
  try {
    listing = execFileSync('npm', ['ls', '--omit=dev', '--all', '--parseable'], { cwd: dir, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024, stdio: ['ignore', 'pipe', 'ignore'] });
  } catch (err) {
    if (!err.stdout) throw err;
    listing = err.stdout;
  }
  const paths = listing.split('\n').filter(Boolean).slice(1);
  const seen = new Map();
  for (const p of paths) {
    const file = join(p, 'package.json');
    if (!existsSync(file)) continue;
    const pkg = JSON.parse(readFileSync(file, 'utf8'));
    if (!pkg.name) continue;
    seen.set(`${pkg.name}@${pkg.version}`, { name: pkg.name, version: pkg.version, license: licenseOf(pkg), repo: repoOf(pkg) });
  }
  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
}

const SECTIONS = [['api', 'API image (`api/`)'], ['web', 'Web image (`web/`)']];
let out = `# Third-party notices

Glou is released under the licence in [LICENSE](LICENSE). The Docker images also
contain the third-party software below, each under its own licence. This file is
generated by \`node scripts/generate-notices.mjs\` from the **production**
dependencies of \`api/\` and \`web/\`; do not edit it by hand.

The licence texts ship with each package (\`node_modules/<name>/LICENSE\`, inside
the images) and at the repository linked below.

## Base images

| Image | Used for | Licence |
|---|---|---|
| \`node:20-alpine\` | api and web runtime | Node.js: MIT; Alpine Linux: various open-source licences |
| \`postgres:15-alpine\` | database | PostgreSQL Licence |
| \`ollama/ollama\` | optional label scan (\`scan\` profile) | MIT |

The \`postgresql-client\` and \`openssl\` packages are added to the API image from Alpine.

`;

const flagged = [];
for (const [app, title] of SECTIONS) {
  const deps = collect(app);
  out += `## ${title}\n\n${deps.length} packages.\n\n| Package | Version | Licence | Source |\n|---|---|---|---|\n`;
  for (const d of deps) {
    out += `| ${d.name} | ${d.version} | ${d.license.replace(/\|/g, '/')} | ${d.repo} |\n`;
    if (/hippocratic|unknown|gpl|sspl|busl|commons-clause/i.test(d.license) && !/lgpl/i.test(d.license)) flagged.push(`${app}: ${d.name}@${d.version} (${d.license})`);
  }
  out += '\n';
}
writeFileSync(join(root, 'THIRD_PARTY_NOTICES.md'), out);
if (flagged.length) console.log('Licences to review:\n' + flagged.join('\n'));
console.log(`THIRD_PARTY_NOTICES.md written (${out.split('\n').length} lines)`);
